version: '3.8'

name: spark-trading
services:
    exchange:
        build:
            dockerfile: modules/exchange/Dockerfile
        environment:
            PORT: '8080'
            H2_FILE: '/storage/db'

    admin:
        build:
            dockerfile: modules/admin/Dockerfile
        environment:
            PORT: '8080'
            H2_FILE: '/storage/db'
            EXCHANGE_SERVER: 'http://exchange:8080/'
        depends_on:
        - exchange

    nginx:
        image: nginx:latest
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
        - '8080:8080'
        - '3000:3000'
        depends_on:
        - admin
        - exchange