###
GET http://localhost:8080/admin/healthcheck

###
GET http://localhost:8080/admin/users?page=0&size=20

###
POST http://localhost:8080/admin/users?name=DIMA&balance=1000

###
GET http://localhost:8080/admin/users/0b027cf3-8959-4b7a-afda-e75d5c1da136

###
DELETE http://localhost:8080/admin/users/0b027cf3-8959-4b7a-afda-e75d5c1da136

###
PATCH http://localhost:8080/admin/users/0b027cf3-8959-4b7a-afda-e75d5c1da136/balance?amount=-100

###
POST http://localhost:8080/admin/users/0b027cf3-8959-4b7a-afda-e75d5c1da136/order/YAN?amount=-10